<style>
.msgbod{
	display: inline-block;
    position: relative;
    top: 0;
    bottom: 0;
    left: 20%;
    right: 20%;
    width: 750px;
    height: 120px;
    margin: auto;
}
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}
.page-title-wrapper
{
    text-align: center;
}


</style>

<h3 style="text-align: center;">

  We have received your payment successfully.

</h3>
<p> 

   We'll email you an order confirmation with dtails and traking info. 

</p>

<div class="main">
    <div class="primary">
        <a href="\" style="text-align: center;"><button class="action primary continue">Continue Shopping</button></a>
    </div>
</div>